name: Execute Java sample testcases with Maven and publist report in github pages

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [on-push]

jobs:
  build:
    # This will spinup ubuntu based VM instance
    runs-on: ubuntu-latest

    steps:
    - name: pull the project in to the runner
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Start selenoid
      uses: n-ton4/selenoid-github-action@master
      id: start-selenoid
      continue-on-error: false
      with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1
  
    - name: Build with Maven
      run: mvn clean test
   
    - name: Add Artifact to publish
      run: |
       cd src/test/resources/cucumber-reports/.
       
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
       name: Cucumber Reports
       path: src/test/resources/cucumber-reports/
       
  deploy:
   runs-on: ubuntu-latest
   needs: build
   environment:
         name: github-pages
         url: ${{steps.deployment.outputs.page_url}}
         
   steps:
         - uses: actions/download-artifact@main
           with:
            name: Cucumber Reports
            path: .
         - uses: actions/configure-pages@v1
         - uses: actions/upload-pages-artifact@v1
           with:
            path: .
         - id: deployment
           uses: actions/deploy-pages@main
